name: Build and Test XGBSE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.ci -t xgbse-test .

      - name: Run tests
        run: docker run --rm xgbse-test
